name: "Empty File DB on Main Push"

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  empty_db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Empty DB
        run: 
          echo '' > musipy.db
